package core

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// PrettyReport renders a CrapReport as a human-readable text block: leading
// metadata, an optional notes section, a summary table, then the top-N methods
// by wCRAP descending. Methods above threshold are marked with `!` so the
// table doubles as a "where to go next" guide even when nothing is strictly
// crappy.
func PrettyReport(report CrapReport, topN int) string {
	var b strings.Builder
	b.WriteString(header(report))
	b.WriteString("\n")
	if len(report.Notes) > 0 {
		b.WriteString(notesSection(report))
		b.WriteString("\n")
	}
	b.WriteString(summarySection(report))
	b.WriteString("\n")
	b.WriteString(topMethods(report, topN))
	return b.String()
}

// JSONReport encodes the report as indented JSON. Field order is fixed by the
// struct definitions (alphabetical) to keep diffs stable in CI.
func JSONReport(report CrapReport) (string, error) {
	out, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return "", err
	}
	return string(out), nil
}

// ErrorTextLine renders an error envelope as a single-line CLI message.
func ErrorTextLine(env ErrorEnvelope) string {
	return fmt.Sprintf("%s: [%s] %s", ToolName, env.Code, env.Message)
}

// ErrorJSON renders an error envelope as JSON: {"error": {...}}.
func ErrorJSON(env ErrorEnvelope) string {
	out, _ := json.MarshalIndent(map[string]ErrorEnvelope{"error": env}, "", "  ")
	return string(out)
}

func header(report CrapReport) string {
	var coverageLine string
	switch {
	case report.CoverageDataPath != nil:
		coverageLine = *report.CoverageDataPath
	case report.CoverageAvailable:
		coverageLine = "(generated by go test — cleaned up after run)"
	default:
		coverageLine = "(none — coverage assumed 0%)"
	}
	return fmt.Sprintf("%s %s — schema %s\n", ToolName, report.ToolVersion, report.SchemaVersion) +
		fmt.Sprintf("source:    %s\n", report.SourceRoot) +
		fmt.Sprintf("coverage:  %s\n", coverageLine) +
		fmt.Sprintf("threshold: %.1f\n", report.Threshold)
}

func notesSection(report CrapReport) string {
	var b strings.Builder
	b.WriteString("Notes\n")
	for _, note := range report.Notes {
		fmt.Fprintf(&b, "  • %s\n", note)
	}
	return b.String()
}

func summarySection(report CrapReport) string {
	s := report.Summary
	var b strings.Builder
	b.WriteString("Summary\n")
	fmt.Fprintf(&b, "  files:     %d\n", s.FileCount)
	fmt.Fprintf(&b, "  types:     %d  (crappy: %d)\n", s.TypeCount, s.CrappyTypeCount)
	fmt.Fprintf(&b, "  methods:   %d  (crappy: %d)\n", s.MethodCount, s.CrappyMethodCount)
	fmt.Fprintf(&b, "  avg crap:  %.2f\n", s.AverageCrap)
	fmt.Fprintf(&b, "  max crap:  %.2f\n", s.MaxCrap)
	fmt.Fprintf(&b, "  avg cyc:   %.2f\n", s.AverageComplexity)
	fmt.Fprintf(&b, "  avg cog:   %.2f\n", s.AverageCognitiveComplexity)
	fmt.Fprintf(&b, "  avg wt:    %.2f\n", s.AverageWeightedComplexity)
	if s.WeightedCoverage != nil {
		fmt.Fprintf(&b, "  coverage:  %.1f%%\n", *s.WeightedCoverage)
	} else {
		b.WriteString("  coverage:  unavailable (run without --no-coverage to gather it)\n")
	}
	return b.String()
}

func topMethods(report CrapReport, topN int) string {
	ranked := append([]MethodCrap{}, report.Methods...)
	sort.SliceStable(ranked, func(i, j int) bool { return ranked[i].Crap > ranked[j].Crap })
	if len(ranked) > topN {
		ranked = ranked[:topN]
	}
	if len(ranked) == 0 {
		return "No methods analyzed.\n"
	}
	crappyTotal := report.Summary.CrappyMethodCount
	thresholdText := fmt.Sprintf("%.1f", report.Threshold)
	var b strings.Builder
	if crappyTotal > 0 {
		fmt.Fprintf(&b, "Top methods by wCRAP (%d above threshold %s, marked !)\n", crappyTotal, thresholdText)
	} else {
		fmt.Fprintf(&b, "Top methods by wCRAP (none above threshold %s — ranked hotspots to watch)\n", thresholdText)
	}
	for _, m := range ranked {
		marker := " "
		if m.IsCrappy {
			marker = "!"
		}
		fmt.Fprintf(&b, "%s %s  cyc=%s cog=%s wt=%s cov=%s%%  %s:%d  %s\n",
			marker,
			padStart(fmt.Sprintf("%.2f", m.Crap), 7),
			padEnd(fmt.Sprintf("%d", m.Complexity), 3),
			padEnd(fmt.Sprintf("%d", m.CognitiveComplexity), 3),
			padStart(fmt.Sprintf("%.2f", m.WeightedComplexity), 5),
			padStart(fmt.Sprintf("%.1f", m.Coverage), 5),
			m.File, m.Line, m.QualifiedName,
		)
	}
	return b.String()
}

func padStart(s string, width int) string {
	if len(s) >= width {
		return s
	}
	return strings.Repeat(" ", width-len(s)) + s
}

func padEnd(s string, width int) string {
	if len(s) >= width {
		return s
	}
	return s + strings.Repeat(" ", width-len(s))
}
